config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  devise_for :users
  get 'home/about' => 'home#about', as: "about"


  resources :books, only: [:new, :create, :index, :show, :destroy]
  get "books/:id/edit" => "books#edit"
  post "books/:id/edit" => "books#edit", as:"edit_book"
  patch "books/:id" => "books#update", as:"update_book"
  delete "books/:id" => "books#destroy", as: "destroy_book"

  resources :users, only: [:show, :edit, :index, :update]
  end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, uniqueness: true,
                    length: {maximum: 200}


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :correct_book, only:[:edit, :update]
  def index
    @books = Book.all
    @book = Book.new
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:success] = "You have created book successfully."
      redirect_to book_path(@book.id)

    else
      @books = Book.all
      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
    @books = Book.all
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to book_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book.id)

    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_book
    @book = Book.find(params[:id])
     unless @book.user == current_user
     redirect_to books_path
     end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>

      <%= image_tag book.user.get_profile_image("100x100") %>

      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= book.user.name %></th>
          </tr>
          <th>introduction</th>
          <th><%= book.user.introduction %></th>
        </tbody>
      </table>

      <div class="row">
        <%= link_to edit_user_path(book.user.id), class: "btn btn-outline-secondary btn-sm btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>


      <h2 class="mt-3">New book</h2>
        <%= form_with model: Book.new, local:true do |f| %>
        <div class="form-group">
          <label>Title</label><br>
          <%= f.text_field :title %>
        </div>

        <div class="form-group">
          <label>Opinion</label><br>
          <%= f.text_area :body %>
        </div>

         <div class="form-group">
         <%= f.submit "Create Book", :class=>"btn btn-success" %>
         </div>
        <% end %>

    </div>

app/views/books/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto" >
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
          <div id="error_explanation">
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
          </div>
      <% end %>

      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title %>
        </div>

        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body %>
        </div>

        <div class="form-group">
         <%= f.submit "Update Book", :class=>"btn btn-success" %>
         </div>
        <% end %>

        <%= link_to "Show", book_path(@book) %> |
        <%= link_to "Back", books_path %>


    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
  </div>


<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <h2>User info</h2>

      <%= image_tag current_user.get_profile_image("100x100") %>

      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tbody>
      </table>

       <div class="row">
        <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-sm btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>


      <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label>Title</label><br>
          <%= f.text_field :title %>
        </div>

        <div class="form-group">
          <label>Opinion</label><br>
          <%= f.text_area :body %>
        </div>

         <div class="form-group">
         <%= f.submit "Create Book", :class=>"btn btn-success" %>
         </div>
        <% end %>

    </div>


    <div class="col-md-8 offset-md-1">
      <p id="notice"></p>
      <h2>Books</h2>
         <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image("40x40") %>
                <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<%= render 'book', book: @book %>

 <div class="col-md-8 offset-md-1">
      <p id="notice"></p>
      <h2>Book detail</h2>
         <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
              <tr>
                <td><%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image("40x40") %><br>
                <%= @book.user.name %>
                </td>
                <td><%= link_to @book.title, book_path(@book.id) %></td>
                <td><%= @book.body %></td>

                <% if @book.user.id == current_user.id %>
                <td>
                 <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
                </td>
                <td>
                 <%= link_to "Destroy", book_path, class: "btn btn-sm btn-danger", method: :delete %>
                </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>

    </div>