config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  devise_for :users
  get 'home/about' => 'home#about', as: "about"


  resources :books, only: [:new, :create, :index, :show, :destroy]
  get "books/:id/edit" => "books#edit"
  post "books/:id/edit" => "books#edit", as:"edit_book"
  patch "books/:id" => "books#update", as:"update_book"
  delete "books/:id" => "books#destroy", as: "destroy_book"

  resources :users, only: [:show, :edit, :index, :update]
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">

    <header class="bg-dark">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarDropdown" aria-controls="navbarDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user), class: "nav-link text-white" do %>
                  <i class="fas fa-home"></i>
                  Home
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to users_path, class:"nav-link text-white" do %>
                  <i class="fas fa-users"></i>
                  Users
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to books_path, class:"nav-link text-white" do %>
                  <i class="fas fa-book-open"></i>
                  Books
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-white" do %>
                  <i class="fas fa-sign-out-alt"></i>
                  Log out
                  <% end %>
                </li>

              <% else %>
                <li class="nav-item">
                  <%= link_to "/", class:"nav-link text-white" do %>
                  <i class="fas fa-home"></i>
                  Home
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to "/home/about", class:"nav-link text-white" do %>
                  <i class="fas fa-link"></i>
                  About
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to new_user_registration_path, class:"nav-link text-white" do %>
                  <i class="fas fa-user-plus"></i>
                  Sign up
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to new_user_session_path, class:"nav-link text-white" do %>
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                  <% end %>
                </li>

              <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>
   <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
   <% end %>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>